CREATE TABLE Items (
	ItemId VARCHAR(45) NOT NULL PRIMARY KEY, 
	VectorPath VARCHAR(255) NOT NULL,
	PngPath VARCHAR(255) NOT NULL,
	ImageBrightness FLOAT,
);


CREATE TABLE Tags (
	TagId VARCHAR(45) NOT NULL PRIMARY KEY, 
	Tag VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci NOT NULL,
	ItemId VARCHAR(45) NOT NULL,
	INDEX (Tag, ItemId)
	);
