CREATE TABLE items (
	item_id VARCHAR(45) NOT NULL PRIMARY KEY, 
	vector_path VARCHAR(255) NOT NULL,
	png_path VARCHAR(255) NOT NULL
);


CREATE TABLE tags (
	tag_id VARCHAR(45) NOT NULL PRIMARY KEY, 
	tag VARCHAR(255) CHARACTER SET UTF8MB4 COLLATE utf8mb4_unicode_ci NOT NULL,
	item_id VARCHAR(45) NOT NULL
	);
