CREATE TABLE tattoos (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, img_id(VARCHAR(255) NOT NULL);
ALTER TABLE tattoos AUTO_INCREMENT = 10000; 



CREATE TABLE tags (tag_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, tag VARCHAR(255) NOT NULL);
ALTER TABLE tags AUTO_INCREMENT = 1000; 