CREATE TABLE tattoos (
	tattoo_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	vector_path VARCHAR(255) NOT NULL,
	png_path VARCHAR(255) NOT NULL
);
ALTER TABLE tattoos AUTO_INCREMENT = 1000; 



CREATE TABLE tags (
	tag_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	tag VARCHAR(255) NOT NULL,
	tattoo_id INT NOT NULL
	);
ALTER TABLE tags AUTO_INCREMENT = 100; 